[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[[profile.default.fs_permissions]]
access = "read"
path = "./testdata"

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.2"
vlayer = "0.1.0-nightly-20241115-70dfc11"

[dependencies.risc0-ethereum]
version = "1.0.0"
url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.0.0-soldeer-no-remappings/contracts.zip"

[soldeer]
remappings_generate = true
remappings_regenerate = true
fs_permissions = [{ access = "read", path = "./testdata"}]
